name: Biome CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno (v2)
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run Biome CI
        run: deno run -A npm:@biomejs/biome@latest ci ./src --reporter=github
