name: Deno CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint_typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno (v2)
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Type check (ts)
        run: deno task type-check

      - name: Lint (biome via deno)
        run: deno task lint

  build:
    runs-on: ubuntu-latest
    needs: lint_typecheck
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno (v2)
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build site
        run: deno task build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-dist
          path: dist
